# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Docs
    url: docs/
    weight: 20
  - name: Schedule
    url: docs/schedule/
    weight: 30
  - name: Assignments
    url: docs/assignments/
    weight: 40
  - name: Policies
    url: docs/policies/
    weight: 50

sidebar:
  - identifier: more
    name: Course links
    params:
      type: separator
    weight: 1
  - identifier: github
    name: "GitHub repository"
    url: "https://github.com/WING-NUS/cs4285-website"
    weight: 2
  - identifier: nus
    name: "NUS"
    url: "https://www.nus.edu.sg/"
    weight: 3
