# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Go to Canvas
    url: https://canvas.nus.edu.sg/courses/98339
    weight: 5
  - name: Home
    url: /
    weight: 10
  - name: Schedule
    url: docs/schedule/
    weight: 30
  - name: Assignments
    url: docs/assignments/
    weight: 40
  - name: Grading
    url: docs/grading/
    weight: 50
  - name: Policies
    url: docs/policies/
    weight: 60

sidebar:
  - identifier: more
    name: Course links
    params:
      type: separator
    weight: 1
  - identifier: github
    name: "GitHub repository"
    url: "https://github.com/WING-NUS/cp4285-website"
    weight: 2
  - identifier: nus
    name: "NUS"
    url: "https://www.nus.edu.sg/"
    weight: 3
